### ISSUE TITLE
video voice issue

### ISSUE THREAD

**Issue by whitestorm007** [thim0o/gdrive-cfworker-videostream#1]
in some video there is no audio playing ..

**Comment by thim0o** [comment]
That's an issue with the file you are trying to play or the software you are using to play it. 
Maybe your media player probably doesn't support the right formats. 
gdrive-cfworker-videostream provides access to the raw file so I don't think it can be causing this issue.

**Comment by whitestorm007** [comment]
you are right buddy , issue is in the file format (MKV) , and HTML5 dosen't support mkv so ...
